// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sendmail.proto

package jp.co.neosystem.grpc;

public interface MailReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sendmail.MailReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 status = 1;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
