// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sendmail.proto

package jp.co.neosystem.grpc;

public final class Sendmail {
  private Sendmail() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sendmail_MailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sendmail_MailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sendmail_MailReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sendmail_MailReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016sendmail.proto\022\010sendmail\"F\n\013MailReques" +
      "t\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007subject\030\003" +
      " \001(\t\022\014\n\004text\030\004 \001(\t\",\n\tMailReply\022\016\n\006statu" +
      "s\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2@\n\010SendMail\0224\n\004" +
      "Send\022\025.sendmail.MailRequest\032\023.sendmail.M" +
      "ailReply\"\000B\030\n\024jp.co.neosystem.grpcP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sendmail_MailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sendmail_MailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sendmail_MailRequest_descriptor,
        new java.lang.String[] { "From", "To", "Subject", "Text", });
    internal_static_sendmail_MailReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sendmail_MailReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sendmail_MailReply_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
